session_name: tree-view
suppress_history: false
windows:
  - layout: even-horizontal
    panes:
      - yarn run dev
      - yarn run serve
  - panes:
      - ${EDITOR} -S
  - panes:
      - shell_command:
          - git fetch
          - git status
